### ISSUE TITLE
P1

### ISSUE THREAD

**Issue by pujiaxun** [Learning-makes-me-happy/web_tasks#1]
`cout<<"µÚ "<<i+1<<" ÐÐ: "<<f[i]<<endl;`

这里面的µÚ ÐÐ符号是什么东东？

**Comment by Learning-makes-me-happy** [comment]
中文乱码了，本该输出”第i个数为：“。应该是编译器的编码格式不对，dev新建的文件为gb2312编码，晚上回去设置一下。

**Comment by pujiaxun** [comment]
OK～
